### ISSUE TITLE
Does not run on Safari

### ISSUE THREAD

**Issue by SergiusIW** [SergiusIW/gate#5]
When compiled to WebAssembly, the game does not seem to run in a Safari browser, at least on iPhone. The error message seems to indicate that Safari does not support Ogg Vorbis audio. More investigation is required. One possible solution might be to use mp3 audio as a backup if ogg is not supported.

**Comment by kud1ing** [comment]
On macOS at 50% loaded i see the exception `Exception with thrown value: TypeError: readCookie is not a function. (In 'readCookie()', 'readCookie' is undefined)` in `readCookieBytes()`.

Only after continuing the page displays `An exception was thrown: failed to load music0.ogg`.

So maybe this is not OGG related?

**Comment by SergiusIW** [comment]
The issue has been fixed in version 0.6.3.
